# Introduction

The purpose of this book is to serve as a guide for training new team members and colleagues on how we do R/Bioconductor-powered Team Data Science. 

As a team, we run [Data Science guidance sessions](#data-science-guidance-sessions) where we help others navigate the world of data science. Through those sessions we identify concepts that we might need to explain better and this book is where we concentrate all our knowledge. Thus it is continuously modified and expanded. We often refer others to this specific chapters of this book, which in a way is a gloried collection of bookmarks with some of our own explanations.

We constantly create new content to share what we are learning or working on, which you might be interested in. In particular, we:

* run the [LIBD rstats club](http://research.libd.org/rstatsclub/) which you can find on Twitter as [LIBDrstats](https://twitter.com/LIBDrstats) (check the [rstats club schedule](https://docs.google.com/spreadsheets/d/1is8dZSd0FZ9Qi1Zvq1uRhm-P1McnJRd_zxdAfCRoMfA/edit?usp=sharing))
* discuss papers and software in our [team meetings](#team-meetings) (check our [schedule](https://docs.google.com/spreadsheets/d/1r6552ySisg7_KpmJmChOvLHVWdMmss3bncEf2jqIM9k/edit?usp=sharing))
* organize R/Bioconductor data science [bootcamps](#rbioconductor-data-science-bootcamps)

You can find our videos on **YouTube** at [LeonardoColladoTorres/playlists](https://www.youtube.com/c/LeonardoColladoTorres/playlists).

<a class="twitter-timeline" href="https://twitter.com/LIBDrstats?ref_src=twsrc%5Etfw">Tweets by LIBDrstats</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

If you find any typos or issues, please let us know through [/github.com/lcolladotor/bioc_team_ds](https://github.com/lcolladotor/bioc_team_ds). Thank you!
