# Onboarding

If you are either new to my team or [LIBD](https://www.libd.org/), you might this page useful.

On your first few weeks, you will be acquiring a lot of information about how we work, how we organize our work, where things are located, scientific background on the topic(s) you will be working on, as well as configuring your computer so you can work efficiently with the resources we have available. As part of this process, you will likely get a LIBD laptop and will need to spend time configuring it before you can do a lot of work.

Some of the content here comes from [jaffe_onboarding](http://research.libd.org/jaffe_onboarding), which was actively used from Sep 8, 2019 till Sep 2020.

As you'll see, there is a lot of information on this page. If you are overwhelmed, schedule a [Data Science guidance session](#data-science-guidance-sessions) and we'll help you get started by pointing you to the relevant parts appropriate to you. When in doubt, schedule a DSgs! We only list when we are available, so if we are not, you'll notice it on Calendly. Planning ahead is always useful and you should feel free to ask us for help.


## Basic work expectations

This might be your first job experience which is very exciting, but also different from being a student. You will thus need to learn to work in our team and maybe adapt some of your behavior. Ultimately, communication will be your friend to avoid any misunderstandings such as different expectations. There are also some rules you will have to follow, which are aimed at making sure we all are on the same playing field. The following are some team guidelines I have, but you should also follow the LIBD Employee Handbook which you can find through [Paylocity](https://www.paylocity.com/) under the "Company" section after you log in.

* Work 40 hours per week. The employee handbook states: _The Lieber Institute’s normal business hours are 8:30 a.m. to 5:30 p.m., Monday through Friday with an hour included for lunch and breaks._. That’s exactly 8 work hours per day, and 40 work hours per week.
  * You can measure this by installing the free version of [RescueTime](https://www.rescuetime.com/).
* Minimize all distractions on the 8 work hours.
  * Avoid checking social media or any other lurking activities. You can put your phone in "work mode" ("focus" for iPhone) to silence all notifications as well. If you need to do something else, notify me or request time off through [Paylocity](https://www.paylocity.com/) when appropriate.
* Aim to achieve a weekly productivity score on [RescueTime](https://www.rescuetime.com/) of 70 or above (ideally over 80).
  * I have `docs.google.com/#document`, `terminal (iterm2)`, and `rstudio` listed as "very productive". Then `slack`, `mail.libd.org` as "productive". I have `zoom.us` as "very distracting" since I'm personally trying to de-incentivize having meetings all day, but for you that might be different.
* Independently perform basic job responsibilities without instruction.
  * Keep a notebook with you to take notes when necessary.
  * Maintain ongoing list of daily to do items.
  * Optionally post your to dos on the respective Slack channels by 9:30 am each morning (10:30 am when we have 9-10 am meetings). Doing so can help the most in your first few months at the team, so we can identify how to best help you.
* Write code daily and version control it on Git/[GitHub](https://github.com/LieberInstitute). If writing academic papers, then post equivalent updates on Slack.
  * Make at least 10 commits per day, with 15 per day being the ideal number. That’s from 5 commits per 2 hour coding session as noted at ["project feedback"](project-feedback), with at least 3 such sessions per day. 
  * If you spend time writing part of an academic manuscript, then post bullet point updates on the respective Slack channel.
* If you spend more than 15 minutes trying to solve something and are not making any more progress, ask a question about it on a Slack channel (not direct messages) with as much information needed to help you.
  * Don't use direct messages (DMs) on Slack, as multiple people can very likely help you and they won't be able to do so through DMs.
  * For R code, remember to use `reprex` like we mention at ["how to ask for help"](how-to-ask-for-help).
  * You could also request help sessions from team members through the [Data Science guidance sessions](#data-science-guidance-sessions) system.
* Communicate your reasoning and thought process. Respond to your colleagues in appropriate time windows.
  * Don’t assume others know what you are thinking: be as verbose as possible. Avoid one liner replies on emails and Slack. Respond to Slack messages within a business hour and to emails from colleagues within a business day. CC me on all replies you send via email.
* Write a summary after every 1 on 1 meeting. Doing so reduces the burden on memorization.
  * Write a bullet point list or make some GitHub issues after every 1 on 1 meeting you have with me or other colleagues.
* Comply with your "at the office" schedule.
  * The exact days will depend on which days you have approval for working remotely (if any at all).
* Read at least one relevant scientific manuscript per week.
  * Write a summary about it on the appropriate Slack channel. Relevant manuscripts are those explaining software/methods you are using, those related to the biological question you are working on, or new software/methods we might want to use for the projects you are working on.
* Work on your main projects at least some portion each day.
  * Avoid cramming work the day before a meeting for a given project. Working the same amount of hours spread throughout the week allows you to identify questions and problems you might need help with, and to have the time to get the required help.
  * I like having blocks of 2 hours where I work on a given project during 1 block of time. Switching projects too frequently is detrimental since it takes some time to refresh your memory and load the relevant data.


## Background knowledge

Below is a list of papers that might provide some useful background information for bulk RNA-seq or DNA methylation. We will also give you a more updated list of background papers to read depending on the project you will be working on. You might find some relevant papers and videos on the [**team presentations schedule**](https://docs.google.com/spreadsheets/d/1r6552ySisg7_KpmJmChOvLHVWdMmss3bncEf2jqIM9k/edit?usp=sharing) and companion YouTube playlist. For example, check this presentation by Louise A. Huuki-Myers on the [Cobos et al, Nature Communications, 2020](https://doi.org/10.1038/s41467-020-19015-1) deconvolution paper.

<iframe width="560" height="315" src="https://www.youtube.com/embed/xpZGn5JM0FQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### RNA-seq

* [RNA-Seq: a revolutionary tool for transcriptomics](https://www.nature.com/articles/nrg2484)
* [Advancing RNA-Seq analysis](https://www.nature.com/articles/nbt0510-421)
* [Differential gene and transcript expression analysis of RNA-seq experiments with TopHat and Cufflinks](https://www.nature.com/articles/nprot.2012.016)
* [TopHat: discovering splice junctions with RNA-Seq](https://academic.oup.com/bioinformatics/article/25/9/1105/203994)
* [TopHat2: accurate alignment of transcriptomes in the presence of insertions, deletions and gene fusions](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2013-14-4-r36)
* [Systematic evaluation of spliced alignment programs for RNA-seq data](https://www.nature.com/articles/nmeth.2722)
* [Assessment of transcript reconstruction methods for RNA-seq](https://www.nature.com/articles/nmeth.2714)
* [Transcriptome and genome sequencing uncovers functional variation in humans](https://www.nature.com/articles/nature12531)
* [Reproducibility of high-throughput mRNA and small RNA sequencing across laboratories](https://www.nature.com/articles/nbt.2702)

### DNAm

_Note_ that we don't work much with DNAm data nowadays, unlike the [jaffe_onboarding](http://research.libd.org/jaffe_onboarding) days. However, this list might still be useful for some.

* [Measuring cell-type specific differential methylation in human brain tissue](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2013-14-8-r94)
* [From promises to practical strategies in epigenetic epidemiology](https://www.nature.com/articles/nrg3405)
* [A data-driven approach to preprocessing Illumina 450K methylation array data](https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-14-293)
* [Epigenetic memory in induced pluripotent stem cells](https://www.nature.com/articles/nature09342)
* [The human colon cancer methylome shows similar hypo- and hypermethylation at conserved tissue-specific CpG island shores](https://www.nature.com/articles/ng.298)
* [Bump hunting to identify differentially methylated regions in epigenetic epidemiology studies](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3304533/)
* [Analysing and interpreting DNA methylation data](https://www.nature.com/articles/nrg3273)
* [DNA methylation: roles in mammalian development](https://www.nature.com/articles/nrg3354)
* [The Key Role of Epigenetics in Human Disease Prevention and Mitigation](https://www.nejm.org/doi/full/10.1056/NEJMra1402513)
* [Charting a dynamic DNA methylation landscape of the human genome](https://www.nature.com/articles/nature12433)
* [Global Epigenomic Reconfiguration During Mammalian Brain Development](https://science.sciencemag.org/content/341/6146/1237905.long)
* [Divergent neuronal DNA methylation patterns across human cortical development: Critical periods and a unique role of CpH methylation](http://dx.doi.org/10.1186/s13059-019-1805-1)


## Commonly used software

We use quite a bit of different software and while we list out some here below, you will want to check the LIBD [**rstats club schedule**](https://docs.google.com/spreadsheets/d/1is8dZSd0FZ9Qi1Zvq1uRhm-P1McnJRd_zxdAfCRoMfA/edit?usp=sharing) and companion YouTube playlist for more recent videos that might be relevant to your situation. For example, this video talks about RStudio and key packages like: `usethis`, `here`, and `sessioninfo`.

<iframe width="560" height="315" src="https://www.youtube.com/embed/XTuJ8vGnzBU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### `bash` and `linux`

You will need to learn the basics of `bash` and `linux` as we work a lot with the high performance computing cluster named [JHPCE](https://jhpce.jhu.edu/), which is a `linux` cluster. A computing cluster is basically a collection of machines (with no monitors) that have more memory than your regular laptop and that you can use for hours/days. That way, you are not limited by the specific properties of your laptop for most of our work.

* [Linux essentials](https://faculty.ucr.edu/~tgirke/Documents/UNIX/linux_manual.html)
* [The Unix Workbench](https://seankross.com/the-unix-workbench/) by [Sean Kross](http://seankross.com).
* [Rsync (Remote Sync): 10 Practical Examples of Rsync Command in Linux](https://www.tecmint.com/rsync-local-remote-file-synchronization-commands/).
* [Linux file permissions](http://windowsbulletin.com/filepermissions/).
* [How To Use Linux Screen -- website 1](https://linuxize.com/post/how-to-use-linux-screen/) and [How To Use Linux Screen -- website 2](https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/).

### `R`

We use `R` quite a bit, and that's actually how this website was made. Here are some useful resources, though you will eventually want to check the [R/Bioconductor Data Science bootcamps](#rbioconductor-data-science-bootcamps) and related resources.

* Download and install [R from CRAN](https://cran.r-project.org/).
* [R 101](http://research.libd.org/rstatsclub/post/r_101/#.XXfwU5NKi50) LIBD rstats blog post by [Carrie Wright](https://carriewright11.github.io/).
* [Download RStudio Desktop](https://www.rstudio.com/products/rstudio/#Desktop).
* [Using the RStudio Terminal](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal).
* RStudio [cheatsheets](https://www.rstudio.com/resources/cheatsheets/) for many things including regular expressions, `purrr` for functional programming, etc.
* [Building Tidy Tools workshop materials](https://rstd.io/tidytools19) by Charlotte Wickham and Hadley Wickham for the rstudio 2019 conference. Materials from other workshops is available [here](https://blog.rstudio.com/2019/02/06/rstudio-conf-2019-workshops/).
* [R Markdown documentation website](https://rmarkdown.rstudio.com/docs/) announced by [Alison Hill](https://twitter.com/apreshill/status/1171290891157307392?s=20).
* [Cookbook for R graphs, 2nd edition](https://r-graphics.org/) with useful `ggplot2` code.
* [Updating R](http://lcolladotor.github.io/2017/05/04/updating-r/#.XXf3hZNKi50) blog post, though also check more recent resources on the LIBD rstats club Google Sheet.
* Tutorial for [building R websites](http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html) by [Emily C Zabor](http://www.emilyzabor.com/). More on R Markdown websites [here](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html), which is how this website was made.

### `python`

* You can use RStudio for Python syntax highlighting and to run code through the integrated terminal window on JHPCE.
* [`reticulate`](https://rstudio.github.io/reticulate/) might be of interest if you are working with Python from R.
* If you are writing an R package that will use Python internally, check out [`basilisk`](https://bioconductor.org/packages/basilisk/).
* If you want to open `SummarizedExperiment` objects in Python as `AnnData` objects, you might be interested in [`zellkonverter`](https://bioconductor.org/packages/zellkonverter/).


## Team communication

Overall, it's important to ask for help. We try to follow the advice from the [you must try, and then you must ask](https://blogs.akamai.com/2013/10/you-must-try-and-then-you-must-ask.html) blog post. Also try to ask in a Slack channel where others might be able to benefit from your answers in the future. If enough people ask about something, we'll try to write a blog post as [advised here](http://varianceexplained.org/r/start-blog/) by [David Robinson](https://twitter.com/drob). For more details, see the [**"how to ask for help"**](how-to-ask-for-help) page.

### GitHub

* [LieberInstitute](https://github.com/LieberInstitute/) is our GitHub organization account. After you've made your GitHub account let your PI, [Bill Ulrich](https://www.libd.org/team/Bill-Ulrich/) or Leonardo Collado-Torres know about your username through Slack so they can add you to the relevant [teams](https://github.com/orgs/LieberInstitute/teams).
* GitHub issues are a useful way to specify tasks for a given project. As an example, check the [libdRSE project](https://github.com/LieberInstitute/libdRSE/issues?utf8=%E2%9C%93&q=).
* [git to know git: an 8 minute introduction](http://research.libd.org/rstatsclub/post/git-to-know-git/#.XXfvXpNKi50) LIBD rstats blog post by [Amy Peterson](http://amy-peterson.github.io/).
* [Happy Git and GitHub for the useR](https://happygitwithr.com/) book by [Jenny Bryan](https://jennybryan.org/), [Jim Hester](https://twitter.com/jimhester_) and other TAs.
* Videos by [Jacob Fiksel](https://jfiksel.github.io/) on how to use Git for [Windows](https://www.youtube.com/watch?v=F_fPEMnr1OQ&feature=youtu.be) and [Mac](https://www.youtube.com/watch?v=kbmSZwK0k-A&t).
* [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) for fixing GitHub repositories that have data files (example, large files) that you want to delete from your history. Use the JHPCE LIBD module for bfg with `module load bfg`.
* [Commit together with co-authors](https://github.blog/2018-01-29-commit-together-with-co-authors/) such that everyone gets recognized GitHub activity for joint work.
* [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords) in commit messages.
* [Merging a pull request](https://help.github.com/en/articles/merging-a-pull-request). Also check [this comment by Yihui Xie](https://github.com/rstudio/blogdown/issues/269#issuecomment-370818782) on how to best submit pull requests. Yihui Xie wrote two blog posts related to that particular series of pull requests [here](https://yihui.name/en/2018/03/second-pull-request/).
* [Syncing a fork](https://help.github.com/en/articles/syncing-a-fork).
* [How can I undo git reset --hard HEAD~1?](https://stackoverflow.com/questions/5473/how-can-i-undo-git-reset-hard-head1).
* [Contributing to the LIBD rstats club](http://research.libd.org/rstatsclub/post/contributing-to-the-libd-rstats-club/#.XXfwBpNKi50) blog post if you want to write another LIBD rstats blog post or use `r BiocStyle::CRANpkg('blogdown')`.

### Slack

* We have multiple Slack workspaces, though the main one we use is the JHU Genomics Slack which has over 500 members. Ask your PI or Leonardo Collado-Torres to add you to that Slack workspace. Our main team channel is [`#libd_team_lcolladotor`](https://jhu-genomics.slack.com/archives/C01AD6PQHNW).
* [Using Slack for Academic Departmental Communication](http://lcolladotor.github.io/2018/06/19/using-slack-for-academic-departmental-communication/#.XXfVrJNKi50) blog post written by Leo and [Stephanie Hicks](https://www.stephaniehicks.com/).
* Preferably ask questions on a project channel such that others involved in the project are able to contribute answers. If it's a more general question, try asking in the [`#libd_helpdesk`](https://jhu-genomics.slack.com/archives/CUYHWV7AA) channel. Beyond our team, you might want to ask for R help at `#rstats` and JHPCE help at `#jhpce`. You might also want to check out `#jobs`, `#jhu_papers`, `#general`, `#funding`, `#diversity`, `#conferences`, `#random`, `#langmead_rss`, among many others.
* For a new project, create a private channel with the prefix `libd_` then invite the team members who are working on the project or might be able to help.
* To integrate a GitHub repository with a Slack channel type in the channel the command `/github subscribe LieberInstitute/RepoName`.
* Slack supports Markdown syntax for your messages, in particular we use a lot the backtick for inline code and the code chunk syntax for multi-line code. Examples:

```
   `inline code` example
    
    ```
    multi
    line
    code
    example
    ```
```

renders into:

`inline code` example
    
```
multi
line
code
example
```

### Team calendar

* We have a team Google Calendar. Ask Leonardo Collado-Torres via Slack to add you to the calendar with your Google account email address (could be your libd one or could be a gmail account). The calendar is linked to [`#libd_team_lcolladotor`](https://jhu-genomics.slack.com/archives/C01AD6PQHNW) and sends reminders to that channel 30 minutes before an event happens.

### Twitter

* [Tackling Twitter as a Graduate Student](https://biomedicalodyssey.blogs.hopkinsmedicine.org/2019/09/tackling-twitter-as-a-graduate-student/) blog post.


## Laptop setup

The ["config files"](#config-files) page contains some relevant links that can help you find some software we frequently use or configuration files. Overall, we use frequently:

* [R](https://cran.r-project.org/)
* [RStudio](https://www.rstudio.com/products/rstudio/download/): for writing R/Python code, executing it at JHPCE through the integrated terminal.
* [Cyberduck](https://cyberduck.io/) or [WinSCP](https://winscp.net/) for browsing JHPCE files and previewing PDF files.
* Git: for version controlling files. See the [install git](https://happygitwithr.com/install-git.html) chapter from _Happy Git and GitHub for the useR_.
* [GitHub](https://github.com/LieberInstitute): for sharing our code within the team and externally, plus to transfer code between your laptop and JHPCE.
* [TextMate](https://macromates.com/) or [Sublime Text](https://www.sublimetext.com/) or some other text editor that has code syntax highlighting. RStudio has this too.
* JHPCE modules: for having a common installation location at JHPCE for software we use. See [jhpce_mod_source](https://github.com/LieberInstitute/jhpce_mod_source) and [jhpce_module_config](https://github.com/LieberInstitute/jhpce_module_config) for more details. 

### JHPCE

Since most analyses we run involve resources larger than those in our laptops, we typically used a high performance computing environment. Particularly,  [JHPCE](https://jhpce.jhu.edu/). Note that the only official pronunciation for JHPCE is by its letters **J-H-P-C-E**.


#### JHPCE account

One of the first things you'll do is [get a JHPCE account](https://jhpce.jhu.edu/register/user/): under "sponsoring organization" scroll all the way down till you find the LIBD PIs such as "Martinowich" (applicable also for members of Stephanie Page and Kristen Maynard's teams) or "Torres" for Leonardo Collado-Torres. You will receive an email with a private link to schedule your appointment at one of the training sessions for new users. They typically have space for 8 people and do the training sessions once every 2 weeks, so you will want to do this early as it can take a while to setup. Even if you are not going to write code but want to see some plots others have made, you will need to get your JHPCE account.

#### JHPCE setup

Once you have your JHPCE account, you will want to set up your laptop and JHPCE to work efficiently. You highly encourage that you use some of the configuration files from the [**"config files"**](#config-files) page.

* Check the LIBD rstats club videos on JHPCE laptop configuration. Though I also highly encourage you to schedule a [Data Science guidance sessions](#data-science-guidance-sessions) to have someone check your configuration files.
  * [macOS](https://youtu.be/UmE1DZe0B8U): macOS setup, which included troubleshooting some steps.
  * [macOS & winOS](https://youtu.be/5pMVb8I6yXI): some macOS and some winOS users joined us for this practice session.
  * [winOS](https://youtu.be/SBM5Oify6e8): this is a very long video, but everything is eventually covered.
* Setup password-less login through [ssh key pairs](https://jhpce.jhu.edu/knowledge-base/authentication/ssh-key-setup/). You will need 4 key pairs.
  * One key pair for your laptop to the JHPCE login node.
  * One key pair from the JHPCE login node to the compute nodes (typically created by JHPCE admins).
  * One key pair from your laptop to GitHub; see their [documentation](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).
  * One key pair from JHPCE to GitHub.
* You should edit your JHPCE `~/.bashrc` and create your JHPCE `~/.inputrc` file following the information we have at the ["config files"](#config-files) page. 
  * You might want to do something similar for your macOS `~/.bashrc` file. Though I lately use a `~/.zshrc` file on my macOS computer.
* You should specify your email on your JHPCE `~/.sge_request` file following the information we have at the ["config files"](#config-files) page.
* You should edit your laptop's and JHPCE `~/.gitconfig` files following the information we have at the ["config files"](#config-files) page.
* We will want to email BitSupport to make sure that your default user group is not `users`, but a more appropriate group such as `lieber_lcolladotor` or `lieber_marmaypag`.
* You will likely want to configure your laptop & JHPCE to be able to use `rmate` to open JHPCE files from the terminal window in TextMate / Sublime Text / other text editors. This will involve editing your laptop's `~/.ssh/config` as well as your JHPCE's `~/.ssh/config` files. See the video below for more information about this process.
* You might be interested in configuring `rmote` to emulate the RStudio plot and help file panels. This will also involve editing your laptop's `~/.ssh/config` as well as your JHPCE's `~/.ssh/config` files.
* You will likely want to edit your laptop's and JHPCE `~/.Rprofile`, `~/.Renviron` configuration files following the information we have at the ["config files"](#config-files) page.
  
<iframe width="560" height="315" src="https://www.youtube.com/embed/LjWr39C1Z_Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

#### JHPCE info

Now that you have your JHPCE account and can access files, you'll want to get familiarized with many parts of JHPCE. You can see the archive of questions people have asked through [`bithelp`](https://lists.johnshopkins.edu/sympa/arc/bithelp) and/or the [`#jhpce`](https://jhu-genomics.slack.com/archives/C074W8800) channel.

* [Environment modules](https://jhpce.jhu.edu/knowledge-base/environment-modules/) are useful so you don't have to install some common software from stratch, such as `R` which you can load using `module load conda_R`.
* Use LIBD modules which you can setup following [these instructions](https://github.com/LieberInstitute/jhpce_module_config#recurrent-usage). [jhpce_mod_source](https://github.com/LieberInstitute/jhpce_mod_source) and [jhpce_module_config](https://github.com/LieberInstitute/jhpce_module_config) are our GitHub repositories for our LIBD modules.
* [Edit your bashrc file for a nicer terminal experience](http://research.libd.org/rstatsclub/post/edit-your-bashrc-file-for-a-nicer-terminal-experience/#.XXfJQ5NKi50) blog post. See the ["config files"](#config-files) page for the latest common configuration files we use.
* `r BiocStyle::Githubpkg('LieberInstitute/sgejobs')` ([documentation](http://lieberinstitute.github.io/sgejobs)): contains helper functions for writing and interacting with SGE jobs at JHPCE.
* [Array and Sequential Cluster Jobs](https://hopstat.wordpress.com/2013/11/05/array-and-sequential-cluster-jobs/). See also `sgejobs::job_single()`.
* [Setting up your computer for bioinformatics/biostatistics and a compedium of resources](http://lcolladotor.github.io/2012/08/23/setting-up-your-computer-for/#.XXft2pNKi50) 2012 blog post. Includes some Mac and Windows tools.
* [Login to the cluster, request a node and change to your project directory in a single command](http://lcolladotor.github.io/2013/12/11/quick-cluster-login-to-interactive-session/#.XXft5JNKi50) 2013 blog post.
* [me: Bad rm, don't delete stuff I didn't want to delete! (rm: well, I do what you tell me to do!)](http://lcolladotor.github.io/2012/11/07/me-bad-rm-dont-delete-stuff-i-didnt-want-to-delete/#.XXft6pNKi50) 2012 blog post.
* [Automatically coloring your R output in the terminal using colorout](http://lcolladotor.github.io/2014/02/17/colorout/#.XXfu65NKi50) blog post on `colorout` which you can access through [jalvesaq/colorout](https://github.com/jalvesaq/colorout) nowadays and install with `remotes::install_github('jalvesaq/colorout')`.
* See ["config files"](#config-files) page for the latest configuration files ^[Outdated: Check Leo's JHPCE configuration files [here](https://github.com/lcolladotor/config_jhpce).].


There were a lot of miscellaneous things about using JHPCE that might save some confusion if you knew now:

* there's a 100G storage limit on your home directory `/users/[yourusername]/`, which will likely fill up very quickly. Most of us have directories under the `/dcs04`, `/dcl01`, and `/dcl02` filesystems, where there is far more space.
 * you generally will want to include the `-cwd` flag in bash scripts. By default, it will default to dumping output files in your home directory, regardless of where you submit the script.
* for scripts/jobs where you are generating large files, you will need to change the maximum writable file size. This is the `h_fsize` flag for bash scripts, which defaults to 10G. See https://jhpce.jhu.edu/knowledge-base/how-to/ for more details.

### macOS

* [Cyberduck](https://cyberduck.io/) for accessing files remotely. With it, you can open any R files at JHPCE with RStudio in your laptop, then open a terminal from RStudio so you can execute your code.
* [Alfred](https://www.alfredapp.com/) for quickly finding files among many other powerful workflows. I highly recommend paying for the power pack, to get access to the most advanced (and time saving) features.
* [Textmate setup (Mac only)](http://research.libd.org/rstatsclub/post/textmate-setup-mac-only/#.XXfvlZNKi50) LIBD rstats 2018 blog post; it's an alternative to using RStudio. The blog post also explains `rmate` which now also exists as a LIBD module that you can load with `module load rmate` at JHPCE. There's also a more [recent video on this topic](https://youtu.be/LjWr39C1Z_Q) on the LIBD rstats club Google Sheet.
* [CriticMarkup](http://criticmarkup.com/).
* [Mac keyboard shortcuts](https://support.apple.com/en-us/HT201236).

### winOS

* [WinSCP](https://winscp.net/) for browsing JHPCE files, previewing PDF files, opening R files on RStudio, etc.
* [putty](https://www.putty.org/) (which comes with WinSCP), for accessing JHPCE through a terminal window.
* [MobaXTerm](https://jhpce.jhu.edu/knowledge-base/mobaxterm-configuration/) combines SSH and SFTP functionality and is fairly simple to set up and use.
* [git for windows](https://gitforwindows.org/) which includes Git Bash. Check [rstudio issue 2224](https://github.com/rstudio/rstudio/issues/2224) for specifics on how to install Git Bash such that it will work with RStudio terminal.

### Any OS

For both macOS and winOS, you might be interested in this older (2012) blog post about my [computers setup](http://lcolladotor.github.io/2012/08/23/setting-up-your-computer-for/#.YzIP0OzMKX0). 


## Commonly used software

You will find a lot of more recent videos an materials for the topics below on the LIBD [**rstats club schedule**](https://docs.google.com/spreadsheets/d/1is8dZSd0FZ9Qi1Zvq1uRhm-P1McnJRd_zxdAfCRoMfA/edit?usp=sharing) / YouTube playlist. See the [Overview](https://lcolladotor.github.io/bioc_team_ds/index.html#overview) page for more details.

For example, you might enjoy the video about Bioconductor or the one on `SummarizedExperiment` / `SingleCellExperiment`.

<iframe width="560" height="315" src="https://www.youtube.com/embed/c0Ch_sXiGDQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/lqxtgpD-heM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Bioconductor

* [Where do I start using Bioconductor?](http://lcolladotor.github.io/2014/10/16/startbioc/#.XXf1QZNKi50) blog post.
* [How to ask for help for Bioconductor packages](http://lcolladotor.github.io/2017/03/06/how-to-ask-for-help-for-bioconductor-packages/#.XXf1YpNKi50) blog post.
* Bioconductor [workflows](https://bioconductor.org/packages/release/BiocViews.html#___Workflow) such as [rnaseqGene](http://bioconductor.org/packages/release/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html) and [sequencing](http://bioconductor.org/packages/release/workflows/vignettes/sequencing/inst/doc/sequencing.html) are very helpful to get started in the RNA sequencing (RNA-seq) field.
* BioC2019 workshops are available [here](https://rebrand.ly/biocworkshops2019). More recently, you might want to use [Orchestra](http://orchestra.cancerdatasci.org/) to find recent workshops and even access them interactively.
* `r BiocStyle::Biocpkg('limma')`: is one of the main packages we use for analyzing data, particularly with the limma-voom method. Check the Bioconductor workflows that explain limma in more detail [here](https://bioconductor.org/packages/release/BiocViews.html#___Workflow).
* `r BiocStyle::Biocpkg('GenomicRanges')`: is the package we use for interacting with genomic data across ranges. Check the [introduction](http://bioconductor.org/packages/release/bioc/vignettes/GenomicRanges/inst/doc/GenomicRangesIntroduction.html) for more information.
* `r BiocStyle::Biocpkg('SummarizedExperiment')`: is the package we use for creating and interacting with `RangedSummarizedExperiment` objects.
* `r BiocStyle::Biocpkg('bsseq')`: is highly useful for analyzing DNA methylation data, particularly whole genome bisulfite sequencing (WGBS) data.
* `r BiocStyle::Biocpkg('Biostrings')`: is useful for dealing with sequence information such as the human genome sequence.

### Lab software

* `r BiocStyle::Githubpkg('LieberInstitute/jaffelab')` ([documentation](http://lieberinstitute.github.io/jaffelab)): contains several functions we've written over the years that we find helpful for different analyses.
* `r BiocStyle::Githubpkg('LieberInstitute/sgejobs')` ([documentation](http://lieberinstitute.github.io/sgejobs)): contains helper functions for writing and interacting with SGE jobs at JHPCE. We have several videos on `sgejobs` at the [**rstats club schedule**](https://docs.google.com/spreadsheets/d/1is8dZSd0FZ9Qi1Zvq1uRhm-P1McnJRd_zxdAfCRoMfA/edit?usp=sharing).
* [jhpce_mod_source](https://github.com/LieberInstitute/jhpce_mod_source) and [jhpce_module_config](https://github.com/LieberInstitute/jhpce_module_config) are our GitHub repositories for our LIBD modules.
* `r BiocStyle::Githubpkg('LieberInstitute/shinycsv')`: allows interactively exploring a table.
* `r BiocStyle::Biocpkg('megadepth')` by David Zhang, Christopher Wilks, et al is an R package for dealing with BigWig files. Check also the older `r BiocStyle::Githubpkg('LieberInstitute/recount.bwtool')`.
* LIBD RNA-seq processing pipeline: [SPEAQeasy](http://research.libd.org/SPEAQeasy/), and [SPEAQeasy-example](http://research.libd.org/SPEAQeasy-example/). See also the [initial version](https://github.com/LieberInstitute/RNAseq-pipeline).
* [`globus`](https://github.com/LieberInstitute/globus): our Globus share endpoints such that others can access our data.


## Meetings of potential interest

* [LIBD rstats club](http://research.libd.org/rstatsclub/#.XXfxTpNKi50) described in more detail on [this blog post](http://research.libd.org/rstatsclub/post/welcome-to-the-libd-rstats-club/#.XXfEtJNKi50).
* Joint genomics meeting: check the [`#joint_group_meeting`](https://jhu-genomics.slack.com/archives/CC4C0BYGH) channel for more information about this bi-weekly (every 2 weeks) meeting across multiple JHU labs.
* Baltimore R Ladies: check the [`#r-ladies`](https://jhu-genomics.slack.com/archives/CAV89BNFK) Slack channel as well as [meetup.com/rladies-baltimore/](https://www.meetup.com/rladies-baltimore/). They also have a [website](https://rladies-baltimore.github.io/) with code from earlier sessions and you can find the [slides here](https://github.com/rladies/meetup-presentations_baltimore).
* JHU Genomics events: check their calendar [here](http://genomics.jhu.edu/events.html). Every year they organize a symposium around October where you can present a poster if you want. They also organize other workshops which you might be interested in signing up for.


### Conferences

* BioC: announced [here](http://bioconductor.org/help/events/).
* ASHG: [website](https://www.ashg.org/).
* CSHL Biology of Genomes (BoG) or Biological Data Science (BDS): through the [CSHL website](https://meetings.cshl.edu/meetingshome.aspx).
* RStudio conf: [website](https://www.rstudio.com/conference/).
* Women in Data Science (has multiple meetings), [website](https://www.widsconference.org/).
* Joint Statistical Meetings (JSM): through the [ASA website](https://www.amstat.org/asa/meetings/home.aspx).

See the [conferences/courses of interest](https://docs.google.com/spreadsheets/d/15toP739T3cGvqz9I2y56USvVT7GU9jkOx1GDKQsbaPY/edit?usp=sharing) Google Sheet for more up to date information.

## Eating nearby

* **North East Market**: it's on [2101 E Monument St](https://goo.gl/maps/Cy7K5LJ3pZx9p3Mr5) which is just a few minutes away walking. You can find a lot of variety there including a Korean stall along the south wall. That stall is pay-by-weight and lots of the dishes are delicious.
* School of Public Health 9th floor salad bar
**[Garden Plate](https://www.yelp.com/biz/garden-plate-baltimore)**: walk two blocks north to [615 N Wolfe St](https://goo.gl/maps/E5yJzcK4EA4mdTB89) or K 3-4 on the [Hopkins East Baltimore Campus map](https://www.hopkinsmedicine.org/the_johns_hopkins_hospital/_docs/jhi_visitors_guide.pdf), then take an elevator on the south side of the building to the 9th floor. The elevators on the north side don't go all the way up to the 9th floor. ^[I haven't checked if it survived the COVID-19 pandemic or got replaced.]
* **[Kabobi](http://www.helmandkabobi.com/)**: Afghan food, really quick for take-out. Popular choices are the lamb or chicken rice bowls, chopped salads, and the veggie rice bowls.
* **Greenhouse**: This is in neighboring Preclinical Teaching Building (PCTB); it's on K2 on the [Hopkins East Baltimore Campus map](https://www.hopkinsmedicine.org/the_johns_hopkins_hospital/_docs/jhi_visitors_guide.pdf). Have someone show the inside way - or go outside and it's just inside the Wolfe/Monument corner entrance. It's a pay-by-weight buffet with salad bar and hot options. Not amazing but great lower cost option, especially if you are going for the lighter weight foods like salad!

### Food trucks

* [**Koko**](https://www.facebook.com/kocotruck/) - Korean food on Tuesdays and Fridays. A lab favorite! Favorites are bulgogi (beef) and tofu dishes.
* **Chowhound** - burgers (incl. veggie).
* Other good ones: Greek truck, Kabob/falafel truck in front of Starbucks

### Other

* Food court inside the hospital with Subway, Einstein Bros, and others. It's on G-H 4 on the [Hopkins East Baltimore campus map](https://www.hopkinsmedicine.org/the_johns_hopkins_hospital/_docs/jhi_visitors_guide.pdf). There's a second one at I6 on the same map.
* Dunkin, Subway, and Chinese places along Monument St.


## Baltimore Life

* ["So you're moving to Baltimore"](https://simplystatistics.org/2013/09/13/so-youre-moving-to-baltimore/) 2013 blog post by [Brian Caffo](www.bcaffo.com).
* The Baltimore Symphony Orchestra has [discount tickets](https://www.bsomusic.org/calendar/special-offers/) which you might be interested in.
* [Live Baltimore](https://livebaltimore.com/) for relevant information that might be useful prior to buying a home.
