# Data Science guidance sessions

Or DSgs for short

## Sign up

If you are interested in a 25 minute Data Science guidance session, please sign up through [this website](TODO) with a session with one of our guides. If this is the first time you are using this or might need more general guidance, sign up with Leo. 

* [Leonardo Collado-Torres](https://github.com/lcolladotor) ([BioC Support](https://support.bioconductor.org/u/6526/))
  - Research interests: RNA-seq, spatial transcriptomics, un-annotated transcriptome.
  - Technologies I use: R/Bioconductor, GitHub, SGE/JHPCE.
  - Learning about: team management, spatial transcriptomics.
* [Arta Seyedian](https://github.com/aseyedia) ([BioC Support](https://support.bioconductor.org/u/YOUR_PROFILE_NUMBER/))
  - Research interests: xx, yy, zz.
  - Technologies I use: aa, bb, cc.
  - Learning about: uu, ii, oo.
* [Joshua M. Stolz](https://github.com/joshstolz) ([BioC Support](https://support.bioconductor.org/u/YOUR_PROFILE_NUMBER/))
  - Research interests: xx, yy, zz.
  - Technologies I use: aa, bb, cc.
  - Learning about: uu, ii, oo.
* [Louise Huuki](https://github.com/lahuuki) ([BioC Support](https://support.bioconductor.org/u/YOUR_PROFILE_NUMBER/))
  - Research interests: xx, yy, zz.
  - Technologies I use: aa, bb, cc.
  - Learning about: uu, ii, oo.
* [Nicholas J. Eagles](https://github.com/Nick-Eagles) ([BioC Support](https://support.bioconductor.org/u/YOUR_PROFILE_NUMBER/))
  - Research interests: xx, yy, zz.
  - Technologies I use: aa, bb, cc.
  - Learning about: uu, ii, oo.
* [Madhavi Tippani](https://github.com/madhavitippani) ([BioC Support](https://support.bioconductor.org/u/YOUR_PROFILE_NUMBER/))
  - Research interests: xx, yy, zz.
  - Technologies I use: aa, bb, cc.
  - Learning about: uu, ii, oo.


## Help us help you

### Framing a question

### Useful information

## Interaction rules

Code of conduct + more things

## DSgs session reports

**TODO**: some type of anonymous automatic weekly report that pulls data from our session logs, might use GitHub Actions & R Markdown websites to build it

## Become a DSgs guide

Non-team members are welcome to join the [DSgs-guides](#dsgs-guide-team-members). This involves a significant time commitment (~ `r round((4 * (25 + 15 + 10) + 30 + 2 * 60 + 30) / 60 + 0.5, 0)` hours per week) and you need to discuss this with your supervisor. These commitments are:

* helping others through DSgs sessions ~ `r 4 * (25 + 15 + 10)` minutes per week ^[We recommend four 25 minute sessions, each with 15 minutes of preparation and 10 minutes of post-meeting wrap up.]
* a weekly 30 minute meeting as explained in [DSgs: feedback](#dsgs-feedback)
* attending the LIBD rstats club (1 hour per week)
* time for self-learning and/or building common resources (~ 1 hour per week)
* (recommended) practice and learn how to help others through the [Bioconductor Support: practice grounds](#bioconductor-support-practice-grounds) (~ 30 min per week)

Additionally, we might have some additional training sessions.

Some potential advantages are:

* access to all our training material, explained in detail at [DSgs-guides](#dsgs-guides)
* a common structure for helping others at LIBD/JHU
* recognition through our DSgs session reports
