# How to ask for help

## Learning from our search history

## Bioconductor Support website

## RStudio Community website

## GitHub issues

## Slack

### JHU/LIBD

#### JHU Genomics Collective

This is our main Slack workspace. Just like `git` commit messages, channels are cheap. The idea is to make one channel per project. Currently, we are adding all team members to each channel even if they are not working on the specific project. Team members not involved in the project should feel free to **mute** the channel. However, by being a part of the channel, they can then see images and code that we are working on, which in some situations can be useful. For example, maybe we figured out how to make a new `plotly` interactive graph in one channel, then others who are curious can get access to that knowledge and incorporate it into their projects.

If you need help use:

* **libd_helpdesk**: for asking general questions to all team members and LIBD collaborators

For team logistics, our channel is:

* **libd_team_lcollado**: meeting reminders, papers we'll discuss and other team logistics

The remaining main Slack channels are:

* **libd_alumni**: for all LIBD past and current members
* **libd_dsgs**: for the [DSgs-guides](#dsgs-guide-team-members) 
* **libd_genomics_martinowich**: a shared channel with the Martinowich lab Slack workspace
* **libd_lunchtrain**: for random topics as well as organizing lunch outings ^[Or remote lunch Zoom sessions.] using the `/lunchtrain` Slack command ^[Start typing the command on Slack and you'll see the help menu pop up for this command which specifies the syntax for using `/lunchtrain`.]
* **libd_pkgs**: for software (mostly R packages) we are making that is not specific to a particular project
* **libd_rstats_club**: for the LIBD rstats club
* **libd_wfg**: for the LIBD Writing Fellowship Group (WFG) which is a type of writing accountability group or writing agraphia group (WAG)

There are also a set of public channels that we use frequently:

* **conferences**
* **containers**: `docker`, `singularity`, etc
* **diversity**
* **funding**
* **general**
* **genomics_journal_club**: a student-run journal club
* **genomics_seminar**: [Genomics at JHU seminars](https://twitter.com/GenomicsAtJHU?s=20)
* **jhpce**: JHPCE users, though also check the [`bithelp`](#bithelp) and [`bitsupport`](#bitsupport) mailing lists
* **jhu_papers**: where we announce papers with JHU authors
* **joint_group_meeting**: a JHU bi-weekly meeting led by Steven Salzberg and JHU colleagues. This is a great meeting to learn about methods work being done across Hopkins for genomics data analysis.
* **lngmead_rss**: a channel where Ben Langmead shares papers he's interested in
* **papers**: general papers of interest
* **r-ladies**
* **random**
* **rstats**: major R announcements and other goodies


#### Martinowich

This is the LIBD Slack workspace used by Keri Martinowich's team. Several of us work closely with her, Kristen Maynard, Stephanie Page and other Martinowich team projects.

#### LIBD Neuropathology

This is the LIBD Slack workspace used by the Neuropathology team. We use it to interact with Amy Deep-Soboslay, Ran Tao, and their teams.

### Bioconductor

### R-Ladies Baltimore

### Misc

#### JHU Biostatistics

#### rOpenSci

#### The CSCCE

#### CDSB

#### LatinR

## Mailing lists

### bithelp

### bitsupport

### Bioc-devel

### R-Sig-Mac


