# How to be a modern scientist

[Jeff Leek](https://bsky.app/profile/jtleek.bsky.social) wrote a book called [**How to be a modern scientist**](https://leanpub.com/modernscientist) that is available through Leanpub. This book compiled and re-arranged advice and ideas Jeff generated in the prior years and shared through the [Simply Statistics blog](https://simplystatistics.org/). While the book is written with academics in mind, particularly graduate students and postdocs, nearly all of the advice in this book applies to us as well. We actively participate in writing academic papers and software, and we work very closely with graduate students and postdocs. We might even advise some through our [Data Science guidance sessions](#data-science-guidance-sessions). Hence being familiar with this knowledge that Jeff curated and developed is important for us.

In the book, Jeff explains why something is important and also provides specific advice on tools he liked to use (in 2016) for implementing these ideas. Most chapters can be read independently, with "paper writing" directly linked to "reading scientific papers". After reading the introduction, choose whichever chapter appeals to you the most in the moment. For some of the chapters, we have more specific information on this book such as:

* _reading scientific papers_ and _scientific talks_ are something we practice weekly on the [Team meetings](#team-meetings)
* _career planning_ was the basis for [Career growth](#career-growth)

The full list of chapters is:

* Introduction
* Paper writing
* Publishing
* Peer review
* Data sharing
* Scientific blogging
* Scientific code
* Social media in science
* Teaching in science
* Books
* Internal scientific communication
* Scientific talks
* Reading scientific papers
* Credit
* Career planning
* Your online identity
* About the author

We do everything in this book, though to different degrees. This book is actually a key part of our _internal scientific communication_. I've also done several of the things Jeff advises **not** to do ;) and maybe that's why they are listed there hehe. Hopefully I've learned over the years though.

<script async class="speakerdeck-embed" data-id="12480a82259a48fc82ad528cfe62b30c" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>

## Bootcamp session

Below you can watch the video of our training session.

<iframe width="560" height="315" src="https://www.youtube.com/embed/93hA-iPWsbs?si=tuX33ZCLVZnj5wgn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

_Note that the [original video](https://youtu.be/rcX-VyxHEXA) was an 1hr 14 min long. The re-edited video shown above is 54 min long after having removed filler words and pauses using Adobe Premier Pro's AI editing features._

Or if you prefer, you can also watch the series of 10 short videos that summarize the above 54 min video. Here's the first short video of the series:

<iframe width="560" height="315" src="https://www.youtube.com/embed/JnZNA2w6u90?si=8ZMFer21WgBYy8ge" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

This series of short 10 videos is also available on [LinkedIn](https://www.linkedin.com/posts/lcollado_bootcamp-howtobeamodernscientist-modernscience-activity-7418941483283701760-QdI3?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAVwMEMBomcSUST_hBDdt_hdo02zu-hZLiA) and [Instagram](https://www.instagram.com/p/DTr61t-DvTW/) if you prefer those platforms.

For more information about Jeff's Leanpub materials, check this [link](https://leanpub.com/u/jtleek).
