# CBDS

[Jeff Leek](https://bsky.app/profile/jtleek.bsky.social) and others educated thousands of people through the [JHU Data Science Specialization Coursera](https://www.coursera.org/specializations/jhu-data-science), yet they noticed that the audience signing up for those courses was dominated with individuals that had access to undergrad and graduate education already. To help people who didn't have those opportunities but who would still benefit from learning data science skills and R, Jeff put together a team including [Aboozar Hadavand](https://twitter.com/ahdvnd), [Shannon E Ellis](https://twitter.com/Shannon_E_Ellis), and many others listed at [Leanpub](https://leanpub.com/universities/set/jhu/cloud-based-data-science) and on the [CDSB website](https://www.clouddatascience.org/team) ^[If you are interested in Data Science education, you should seriously consider joining this team! I can help you get in touch with Jeff if you want.].

This team developed **Cloud-Based Data Science** (CBDS) as well as [CBDS+](https://www.clouddatascience.org/). CBDS is a collection of Leanpub courses, each of them composed of several lessons and quizzes. Each lesson is described in text and slides, but the material is also available as videos. The videos were made using the R package `r BiocStyle::CRANpkg("ari")` by [Sean Kross](https://bsky.app/profile/seankross.com), processing software written by [John Muschelli](https://bsky.app/profile/strictlystat.bsky.social), and a dictionary detailing how to pronounce data science terms made by [Sarah McClymont](https://twitter.com/sarahmcclymont0).

The Leanpub courses are [**available here**](https://leanpub.com/universities/set/jhu/cloud-based-data-science), which can be purchased for a modest fee or even for free. These courses were designed to be accessible by anyone as young as high school graduates. The hardware requirements are as minimum as possible, meaning that they can be taken using a Chromebook and using cloud resources. That is why these courses are the main ones we recommend for new R users. However, don't be tricked into thinking that they don't teach you important skills. For example, there is a full course on how to use git/GitHub that is crucial to our work and that is taught at the end in some other courses. That is, CBDS explains all the practical tools and skills that you will likely need.

## Bootcamp session

To get ourselves familiarized with CBDS and the courses provided by it, we spent one of our 2 hour bootcamp sessions learning about CBDS.

Below you can watch the video of our training session.

<iframe width="560" height="315" src="https://www.youtube.com/embed/_kyfiQePLDk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

For more information about Jeff's Leanpub materials, check this [link](https://leanpub.com/u/jtleek).
