# Career growth

While I would love that the people I've trained continued collaborating with me such that I can depend on them, everyone has different personal goals in mind and directions they want to take. Part of my job is to help you grow in the direction that you are interested in. To do so effectively, I need to hear from you since it's impossible for me to know your thoughts. 

[How to be a modern scientist](https://leanpub.com/modernscientist) by Jeff Leek has a chapter on career planning, which is written with students and postdocs in mind as is an adaptation of [Ben Langmead's postdoc questionnaire](https://github.com/BenLangmead/langmead-lab/blob/master/postdoc_questionnaire.md). However, I still think that most of this chapter applies regardless of your current position. This book is cheap (and you can get it for free) and is part of the recommended material.

## Career planning session

If I'm asking you to have a career planning session with me, please do the following:

1. read the `career planning` chapter by Jeff Leek
2. create a Google document where you answer at least the following questions, then share it to me before the meeting

If we have met in the past, then write your new answers at the top of the document, but leave the older ones there, to remind us both of the progression of your choices over time.

* What is the next step you want to take in your career? ^[Some examples are: acquiring more responsibilities at LIBD, a change in title at LIBD, applying for grad/med school, a postdoc, a faculty job, an industry job.]
  - What are the main requirements? ^[For some jobs and applications you need recommendation letters, for others you need papers, for others you need to pass some type of test, for others you need to give a talk, or there might be specific courses you have to take.]
  - Example job/grad/med school ad links can be useful to identify common requirements or what you like about them.
* What is the time window you have in mind?
* Who are you? Who do you want to be?
  - What do you want people to notice about you?
  - What is the main resource for people to find information about you? ^[You might have a LinkedIn profile, a website, a CV, a blog, a (professional) Twitter account, a GitHub profile, etc.]
* What do you want to learn?
* What are the main projects you want to complete or work on?
* What conferences / seminars / hackathons are you interested in attending?
  - Knowing when they are and what they request for presenting and for scholarships is useful for planning. 

If you feel like other questions from Ben's list are relevant to you, feel free to answer them too.

