# Building Tidy Tools

In order to organize our code, test it, and share it internally and also externally, we write R packages. Some of them we submit them to Bioconductor and share them more widely. There are several R packages that make the process of writing new R packages easier, such as `r BiocStyle::CRANpkg("devtools")`, `r BiocStyle::CRANpkg("usethis")`, `r BiocStyle::CRANpkg("roxygen2")`, and `r BiocStyle::Githubpkg("lcolladotor/biocthis")`. To learn more about `devtools` and friends, we revised the material from the `rstudio::conf(2020)` workshop [**Building Tidy Tools**](https://github.com/rstudio-conf-2020/build-tidy-tools) that was taught by [Charlotte Wickham](https://twitter.com/CVWickham) and [Hadley Wickham](https://twitter.com/hadleywickham). In the LIBD rstats club, we've also used materials from their 2019 workshop.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Today with <a href="https://twitter.com/lcolladotor?ref_src=twsrc%5Etfw">@lcolladotor</a> we finished ✅ learning about <a href="https://twitter.com/hashtag/purrr?src=hash&amp;ref_src=twsrc%5Etfw">#purrr</a> 🐈, functional programming and basics of <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> functions using <a href="https://twitter.com/CVWickham?ref_src=twsrc%5Etfw">@CVWickham</a>&#39;s slides 🤩 from <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> 2019<br><br>📹<a href="https://t.co/X21qSQT8oX">https://t.co/X21qSQT8oX</a><br>📔 <a href="https://t.co/sE849den78">https://t.co/sE849den78</a><br>💻 <a href="https://t.co/ShN6JhGXXC">https://t.co/ShN6JhGXXC</a><a href="https://t.co/i6lmnrbBB5">https://t.co/i6lmnrbBB5</a></p>&mdash; LIBD rstats club (@LIBDrstats) <a href="https://twitter.com/LIBDrstats/status/1294355117916000258?ref_src=twsrc%5Etfw">August 14, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

The _Building Tidy Tools_ workshop is very useful if you want to transition from R user to R developer. If you are a Spanish speaker, you might be interested in our translation of their `rstudio::conf(2019)` workshop at [CDBS](https://github.com/ComunidadBioInfo/cdsb2019).

## Bootcamp sessions

This workshop involves several exercises, which we highly recommend that you try to solve. One of our solutions is [`lahuuki/foofactors2`](https://github.com/lahuuki/foofactors2). Below you can watch the videos of our training sessions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/F0i0E1L4-6k" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/yqyVovQYmxo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
