# (PART) Internal {-}

# Team meetings

Every week we meet for about an hour. The team meeting has three sections:

* [30 min] **Papers & software**: we discuss either a paper or some software. The discussion is lead by a team member and the presentation is made public on [YouTube](https://www.youtube.com/@lcolladotor/playlists) while the discussion is kept private.
* [10 min] **Data Science guidance sessions**: we talk about our sessions and provide internal feedback.
* [20 min] **Help requests**: we give open the floor to discuss anything we need help on from the rest of the team. If you have a topic in mind, add it to the team meeting calendar.

On some occasions we have meetings fully dedicated to:

* A paper or software
* A practice presentation by one of our team members in order to build up and polish our presentation skills. These are typically held during the Summer or prior to specific conferences/LIBD seminars.
* Code written by one of our team members: show us something you've been working on, something you want feedback on, etc. Think of it as a group-level _paired coding_ session.

## Papers & software

Each week, we rotate team members as shown on [this presenters Google Spreadsheet](https://docs.google.com/spreadsheets/d/1r6552ySisg7_KpmJmChOvLHVWdMmss3bncEf2jqIM9k/edit?usp=sharing). That team member is in charge of:

1. finding a paper or a software of interest
2. notifying the group about it at least one week ahead on Slack using the `@channel` tag on the [libd_team_lcolladotor](https://jhu-genomics.slack.com/archives/C01AD6PQHNW) Slack channel
3. preparing a few slides to explain the main concepts to us (plan for a 15 minute presentation)
4. add some quick notes or short summary on the Google Spreadsheet

The rest of the team members are responsible for reading the main PDF of the paper or software. Optionally, members can read the supplementary material, check the GitHub repository(ies) associated with the paper, or public peer reviews (some journals make them public). If the paper was recorded on [the presenters Google Spreadsheet](https://docs.google.com/spreadsheets/d/1r6552ySisg7_KpmJmChOvLHVWdMmss3bncEf2jqIM9k/edit?usp=sharing) at least a week in advance, then team members are expected to have read the paper regardless of whether the presenter sent a reminder Slack message or not.

Overall, all team members have to contribute and be engaged in our continuous learning activities. It is likely useful for everyone to register on Google Sheets for automatic updates ^[I recommend a daily digest instead of an email per update.] from the [the presenters Google Spreadsheet](https://docs.google.com/spreadsheets/d/1r6552ySisg7_KpmJmChOvLHVWdMmss3bncEf2jqIM9k/edit?usp=sharing).

We record that portion of our meeting and make it publicly available through [the presenters Google Spreadsheet](https://docs.google.com/spreadsheets/d/1r6552ySisg7_KpmJmChOvLHVWdMmss3bncEf2jqIM9k/edit?usp=sharing). We then discuss privately our thoughts on the paper or software. Here's our first video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/wuPLVfdZ92Q" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

You can also find the rest of them under the **team lcolladotor** YouTube playlist at [lcolladotor/playlists](https://www.youtube.com/@lcolladotor/playlists).

### Notes

* If you are randomly assigned a date that does not work for you, please get in touch with other team members and find someone who can switch with you. Thank you!
* If you are interested in joining us, please check our [code of conduct](http://research.libd.org/rstatsclub/#coc), and get in touch with [Leonardo](http://lcolladotor.github.io/).

## DSgs: feedback

Every week, the [DSgs-guides](#dsgs-guide-team-members) meet to discuss recent guidance sessions with the following objectives:

1. identify common topics that can be addressed in other venues such as the LIBD rstats club, this book, blog posts, etc
2. ensure consistency of our responses to similar questions
3. identify and address issues with our [DSgs interaction rules](#interaction-rules)

We might identify topics that we need to either train the DSgs-guides on or our LIBD/JHU colleagues, as well as useful R functions/packages that we can write to help us and others.

### Notes

* You don't have to be a part of Leonardo's team to be a DSgs-guide and thus join this meeting.

## Team help

While each team member has an individual weekly meeting, sometimes some problems can be solved with other/fresh eyes looking at them as well as new ideas. If you are having one such problem, this is a great venue to get help for it. This space and time can also be used for asking some quick questions as well as addressing any administration announcements.

## Individual updates

On Mondays at 10:30 am everyone meets with Leo sequentially for 30 min to discuss individual updates. These meetings are useful to talk about what projects take priority on a given week, personal issues, and personal career development decisions such as which conference(s) to attend. Here's a [list of conferences/courses of interest](https://docs.google.com/spreadsheets/d/15toP739T3cGvqz9I2y56USvVT7GU9jkOx1GDKQsbaPY/edit?usp=sharing).

## Project meetings

Here's the list of project meetings and who should attend them:

* Tuesday
  * Moods: Louise, Leo.
    * Optional: Geo.
  * Habenula + multi-ome + Fentanyl: Bukola, Cynthia, Daianna, Louise, Renee, Leo.
    * Optional: Hédia, Nick.
* Wednesday
  * team meeting: everyone.
* Thursday:
  * spatial team meeting: Louise, Nick, Leo.
  * deconvolution: Louise, Leo.
  * NAc spatial: Nick, Leo.
* Friday
  * LIBD rstats club: everyone.
* Unassigned
  * CHESS-BRAIN: Geo, Hédia, Leo.

